[package]
name = "calamine"
version = "0.14.3"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "vba", "office", "ods", "serde"]
categories = ["encoding", "parsing", "text-processing"]

[badges]
travis-ci = { repository = "tafia/calamine" }
appveyor = { repository = "tafia/calamine" }

[dependencies]
byteorder = "1.2.4"
encoding_rs = "0.8.4"
failure = "0.1.2"
failure_derive = "0.1.2"
log = "0.4.3"
serde = "1.0.70"
quick-xml = "0.12.1"
zip = { version = "0.4.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
glob = "0.2.11"
