[package]
name = "calamine"
version = "0.4.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "Excel reader in pure rust"
keywords = ["excel", "xls", "vba", "xml", "office"]
license = "MIT"
readme = "README.md"

[dependencies]
zip = { version = "0.2.0", default-features = false }
quick-xml = "0.4.2"
log = "0.3.6"
encoding = "0.2.33"
byteorder = "1.0.0"
error-chain = "0.8.1"

[dev-dependencies]
glob = "0.2.11"
