[package]
name = "office"
version = "0.7.0"
authors = ["Johann Tuffe"]

[dependencies]
zip = { version = "0.1.19", default-features = false }
quick-xml = "0.4.0"
log = "0.3.6"
encoding = "0.2.33"
byteorder = "0.5.3"
error-chain = "0.5.0"

[dev-dependencies]
env_logger = "0.3.4"
