[package]
name = "office"
version = "0.2.0"
authors = ["Johann Tuffe"]

[dependencies]
zip = { version = "0.1.18", default-features = false }
quick-xml = "0.3.1"
log = "0.3.6"
encoding = "0.2.32"
byteorder = "0.5.3"
error-chain = "0.5.0"

[dev-dependencies]
env_logger = "0.3.4"
