[package]
name = "calamine"
version = "0.15.6"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "vba", "office", "ods", "serde"]
categories = ["encoding", "parsing", "text-processing"]

[badges]
travis-ci = { repository = "tafia/calamine" }
appveyor = { repository = "tafia/calamine" }

[dependencies]
byteorder = "1.3.2"
codepage = "0.1.1"
encoding_rs = "0.8.17"
failure = "0.1.5"
failure_derive = "0.1.5"
log = "0.4.6"
serde = "1.0.99"
quick-xml = { version = "0.16", features = ["encoding", "use-failure"] }
zip = { version = "0.5.3", default-features = false, features = ["deflate"] }

[dev-dependencies]
glob = "0.3"
env_logger = "0.6"
