[package]
name = "office"
version = "0.8.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/office"
documentation = "https://docs.rs/office"
description = "Excel reader"
keywords = ["excel", "vba", "office", "xml"]
license = "MIT"

[dependencies]
zip = { version = "0.1.19", default-features = false }
quick-xml = "0.4.1"
log = "0.3.6"
encoding = "0.2.33"
byteorder = "0.5.3"
error-chain = "0.5.0"

[dev-dependencies]
glob = "0.2.11"
